_wandb:
    value:
        cli_version: 0.25.1
        code_path: code/main.py
        e:
            yrfdziy6b90ffpa2kr8sbgspaemyf34i:
                args:
                    - search=optuna
                    - runtime.wandb.enabled=true
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "142597365760"
                        used: "115858497536"
                email: chirkov.gd@phystech.edu
                executable: /home/Xattta6bI4/miniconda3/envs/nfg_env/bin/python
                git:
                    commit: f9a7ebe5d85e96c5275ffe6a095ab4e6ca56acb1
                    remote: git@github.com:Vladislav-Pov/similarity-sarah.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-65642e9c-aa01-6b54-9940-e7d03971b2f6
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-c6d16bdc-c5c9-e35b-4e92-8c96988384f1
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-093c0e0c-a9ee-3383-ac6d-e6b3d6095c1b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-7a50f6c7-f545-0b4c-f32f-9edb6a7e7eaa
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-91279309-1b26-7c66-694f-a18d2c81fd85
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-5430d3bb-f055-7a03-62f9-36ce1cf238c8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-b2f68da5-f46c-c411-5fca-74699a6a3f94
                    - architecture: Turing
                      cudaCores: 4352
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce RTX 2080 Ti
                      uuid: GPU-d9fc0582-a134-ded0-909d-e88d902ecc0b
                host: opt-mipt
                memory:
                    total: "541031403520"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/Xattta6bI4/similarity-sarah/main.py
                python: CPython 3.10.20
                root: /home/Xattta6bI4/similarity-sarah
                startedAt: "2026-04-13T20:06:41.456766Z"
                writerId: yrfdziy6b90ffpa2kr8sbgspaemyf34i
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 35
                - 41
                - 50
            "2":
                - 1
                - 35
                - 41
                - 50
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
                - 62
            "4": 3.10.20
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
base:
    value:
        algorithm:
            batch_size_clients: 2
            name: batched_nfg_sarah
            num_clients: 10
            num_epochs: 75
            prox_lr: 0.01
            prox_num_steps: 8
            theta: 0.01
        data:
            data_dir: ./data
            name: cifar10
            val_fraction: 0.1
        model:
            name: simple_cnn
            num_classes: 10
        partition:
            name: uniform
        runtime:
            batch_size: 128
            device: auto
            eval_every: 1
            log_every: 1
            num_workers: 2
            wandb:
                enabled: true
                entity: chirkov
                group: null
                job_type: null
                name: null
                project: similarity-sarah
                tags: []
        search:
            batched_nfg_sarah:
                prox_lr:
                    - 0.005
                    - 0.01
                prox_num_steps:
                    - 8
                    - 12
                    - 18
                theta:
                    - 0.005
                    - 0.01
                    - 0.02
            distributed_sarah:
                lr:
                    - 0.005
                    - 0.01
                    - 0.02
            enabled: true
            max_epochs: 150
            method: optuna
            num_trials: 10
            shared:
                batch_size_clients:
                    - 1
                num_epochs: 150
            wandb_group: optuna-20260413-012704
            wandb_project: similarity-sarah
        seed: 42
search_params:
    value:
        batched_nfg_sarah.prox_lr: 0.01
        batched_nfg_sarah.prox_num_steps: 18
        batched_nfg_sarah.theta: 0.01
        distributed_sarah.lr: 0.005
        shared.batch_size_clients: 1
        shared.num_epochs: 150
