wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.20
    cli_version: 0.25.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1776528612
    t:
      1:
      - 1
      - 35
      - 41
      - 50
      2:
      - 1
      - 35
      - 41
      - 50
      3:
      - 2
      - 4
      - 13
      - 15
      - 16
      - 42
      4: 3.10.20
      5: 0.25.1
      13: linux-x86_64
    e:
      jxmrlcibgtcf6hpqzygeuf1wc2ri6i9i:
        os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
        python: CPython 3.10.20
        started_at: '2026-04-18T16:10:11.985007Z'
        args:
        - search=optuna
        - runtime.wandb.enabled=true
        program: /home/Xattta6bI4/similarity-sarah/main.py
        code_path: main.py
        code_path_local: main.py
        git:
          remote_url: git@github.com:Vladislav-Pov/similarity-sarah.git
          commit: 0ccebb889210ff4fde92abfad70b4262b02493c1
        root: /home/Xattta6bI4/similarity-sarah
        host: opt-mipt
        executable: /home/Xattta6bI4/miniconda3/envs/nfg_env/bin/python
        cpu_count: 48
        cpu_count_logical: 48
        gpu_type: NVIDIA A100-PCIE-40GB
        gpu_count: 8
        disk:
          /:
            total: '142597365760'
            used: '116678975488'
        memory:
          total: '541031403520'
        gpu_nvidia:
        - name: NVIDIA A100-PCIE-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-65642e9c-aa01-6b54-9940-e7d03971b2f6
        - name: NVIDIA GeForce RTX 2080 Ti
          memory_total: '11811160064'
          cuda_cores: 4352
          architecture: Turing
          uuid: GPU-c6d16bdc-c5c9-e35b-4e92-8c96988384f1
        - name: NVIDIA A100-SXM4-80GB
          memory_total: '85899345920'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-093c0e0c-a9ee-3383-ac6d-e6b3d6095c1b
        - name: NVIDIA A100-PCIE-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-7a50f6c7-f545-0b4c-f32f-9edb6a7e7eaa
        - name: NVIDIA A100-SXM4-80GB
          memory_total: '85899345920'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-91279309-1b26-7c66-694f-a18d2c81fd85
        - name: NVIDIA A100-PCIE-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-5430d3bb-f055-7a03-62f9-36ce1cf238c8
        - name: NVIDIA A100-PCIE-40GB
          memory_total: '42949672960'
          cuda_cores: 6912
          architecture: Ampere
          uuid: GPU-b2f68da5-f46c-c411-5fca-74699a6a3f94
        - name: NVIDIA GeForce RTX 2080 Ti
          memory_total: '11811160064'
          cuda_cores: 4352
          architecture: Turing
          uuid: GPU-d9fc0582-a134-ded0-909d-e88d902ecc0b
        cuda_version: '12.9'
        writer_id: jxmrlcibgtcf6hpqzygeuf1wc2ri6i9i
base:
  desc: null
  value:
    algorithm:
      name: batched_nfg_sarah
      num_clients: 10
      batch_size_clients: 1
      theta: 0.02
      num_epochs: 100
      prox_num_steps: 50
      prox_lr: 0.002
    data:
      name: cifar10
      data_dir: ./data
      val_fraction: 0.1
    model:
      name: resnet18_32x32
      num_classes: 10
    partition:
      name: uniform
    runtime:
      device: auto
      eval_every: 1
      log_every: 1
      num_workers: 2
      batch_size: 128
      batch_size_server: 128
      batch_size_data_clients: 128
      wandb:
        enabled: true
        project: similarity-sarah
        entity: chirkov
        group: null
        tags: []
        job_type: null
        name: null
    search:
      enabled: true
      method: optuna
      max_epochs: 100
      num_trials: 1
      wandb_project: similarity-sarah
      wandb_group: optuna-20260418-191008
      shared:
        batch_size_clients:
        - 1
        num_epochs: 100
      batched_nfg_sarah:
        theta:
        - 0.02
        prox_lr:
        - 0.002
        prox_num_steps:
        - 50
    seed: 42
search_params:
  desc: null
  value:
    shared.batch_size_clients: 1
    shared.num_epochs: 100
    batched_nfg_sarah.theta: 0.02
    batched_nfg_sarah.prox_lr: 0.002
    batched_nfg_sarah.prox_num_steps: 50
